services:
  postgres-prova:
    image: kartoza/postgis:13-3.1
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db_prova
    volumes:
      - "pg-data-prova:/var/lib/postgresql"      
    networks:
      - prova 
  api:
    build:
      context: ..
      dockerfile: ./presentation/Prova.Api/Dockerfile
    ports:
      - 3333:8080
    depends_on:
      - postgres-prova
    environment:
      - DOTNET_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres-prova;Port=5432;Database=db_prova;User Id=postgres;Password=postgres;Persist Security Info=True;
    volumes:
      - ../src/Prova.Api:/app/build
    restart: on-failure:10
    networks:
      - prova
    command: ["wait-for-it.sh", "postgres-prova:5432", "--", "dotnet", "Prova.Api.dll"]

volumes:
  pg-data-prova:
    driver: local  
networks:
  prova:
    name: prova.networks
    driver: bridge
    
